USE PLANTILLA_v13
GO

ALTER TABLE SIMBOLOSESTRL__1K
ADD CONSTRAINT CK_STRP_DIP_DIR_1K CHECK (
   DIP_DIR >= 0 AND DIP_DIR <= 360
)
GO

ALTER TABLE SIMBOLOSESTRL__1K
ADD CONSTRAINT CK_STRP_DIP_1K CHECK (
   DIP >= 0 AND DIP <= 90
)
GO

ALTER TABLE SIMBOLOSESTRL_10K
ADD CONSTRAINT CK_STRP_DIP_DIR_10K CHECK (
   DIP_DIR >= 0 AND DIP_DIR <= 360
)
GO

ALTER TABLE SIMBOLOSESTRL_10K
ADD CONSTRAINT CK_STRP_DIP_10K CHECK (
   DIP >= 0 AND DIP <= 90
)
GO

ALTER TABLE SIMBOLOSESTRL__2K
ADD CONSTRAINT CK_STRP_DIP_DIR_2K CHECK (
   DIP_DIR >= 0 AND DIP_DIR <= 360
)
GO

ALTER TABLE SIMBOLOSESTRL__2K
ADD CONSTRAINT CK_STRP_DIP_2K CHECK (
   DIP >= 0 AND DIP <= 90
)
GO

ALTER TABLE SIMBOLOSESTRL_25K
ADD CONSTRAINT CK_STRP_DIP_DIR_25K CHECK (
   DIP_DIR >= 0 AND DIP_DIR <= 360
)
GO

ALTER TABLE SIMBOLOSESTRL_25K
ADD CONSTRAINT CK_STRP_DIP_25K CHECK (
   DIP >= 0 AND DIP <= 90
)
GO

ALTER TABLE SIMBOLOSESTRL__5K
ADD CONSTRAINT CK_STRP_DIP_DIR_5K CHECK (
   DIP_DIR >= 0 AND DIP_DIR <= 360
)
GO

ALTER TABLE SIMBOLOSESTRL__5K
ADD CONSTRAINT CK_STRP_DIP_5K CHECK (
   DIP >= 0 AND DIP <= 90
)
GO

ALTER TABLE SIMBOLOSESTRL_50K
ADD CONSTRAINT CK_STRP_DIP_DIR_50K CHECK (
   DIP_DIR >= 0 AND DIP_DIR <= 360
)
GO

ALTER TABLE SIMBOLOSESTRL_50K
ADD CONSTRAINT CK_STRP_DIP_50K CHECK (
   DIP >= 0 AND DIP <= 90
)
GO